# Generated by Django 6.0.4 on 2026-04-20 06:21

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to=app.models.cover_path)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rac_link', models.URLField()),
                ('watch', models.BooleanField(default=False)),
                ('publisher', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.IntegerField(default=1)),
                ('issue', models.IntegerField()),
                ('rac_link', models.URLField()),
                ('file', models.FileField(blank=True, null=True, upload_to=app.models.issue_file_path)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='app.comic')),
            ],
            options={
                'unique_together': {('comic', 'volume', 'issue')},
            },
        ),
    ]
