# Generated by Django 6.0.4 on 2026-05-02 08:05

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to=app.models.cover_path)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('remote_id', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=50)),
                ('monitor', models.CharField(choices=[('all', 'All Issues'), ('future', 'Future Issues'), ('past', 'Past Issues'), ('first', 'First Volume'), ('last', 'Last Volume'), ('none', 'None')], default='all', max_length=15)),
                ('format', models.CharField(default='cbz', max_length=20)),
                ('volume_folder', models.BooleanField(default=True)),
                ('tags', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='app.genre')),
            ],
            options={
                'unique_together': {('remote_id', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_text', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.IntegerField(default=1)),
                ('issue', models.FloatField()),
                ('is_annual', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('remote_id', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=app.models.issue_file_path)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='app.comic')),
            ],
            options={
                'unique_together': {('comic', 'original_text')},
            },
        ),
    ]
