# Generated by Django 6.0.4 on 2026-05-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
