# Generated by Django 6.0.4 on 2026-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_issue_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
