# Generated by Django 6.0.4 on 2026-05-22 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_issue_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on', 'On Queue'), ('downloading', 'Downloading'), ('error', 'Error')], max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('next_try', models.DateTimeField(blank=True, null=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='app.issue')),
            ],
        ),
    ]
