# Generated by Django 6.0.6 on 2026-06-12 19:06

import app.models
import app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_queue_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='issue',
            name='file',
            field=models.FileField(blank=True, null=True, storage=app.storage.PreserveSpacesStorage, upload_to=app.models.issue_file_path),
        ),
    ]
