# Generated by Django 6.0.6 on 2026-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_queue_options_alter_issue_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_type', models.CharField(blank=True, max_length=10, null=True)),
                ('proxy_host', models.CharField(blank=True, max_length=255, null=True)),
                ('proxy_port', models.CharField(blank=True, max_length=255, null=True)),
                ('proxy_username', models.CharField(blank=True, max_length=255, null=True)),
                ('proxy_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
