# Generated by Django 6.0.6 on 2026-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='use_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
