# Generated by Django 6.0.6 on 2026-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_settings_use_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='proxy_port',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
