# Generated by Django 6.0.6 on 2026-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_settings_proxy_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='proxy_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
